import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Design Toolbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Design Toolbox</h1>

        <p className={styles.description}>
          A repository to organise all the different product design tools I
          learn about.
        </p>
        <p className={styles.warning}>
          🚧 Please note this site is still under construction! 🚧
        </p>
        <p className={styles.description}>
          Will add filters to filter by design thinking process stage, its
          stakeholder engagement score, budget, and effort.
        </p>

        <div className={styles.grid}>
          <Link href="/assumption-mapping">
            <a className={styles.card}>
              <h2>Assumption Mapping</h2>
              <p>
                A workshop to map assumptions on a scale of risk and how
                supported they are by evidence.
              </p>
            </a>
          </Link>

          <Link href="/user-journey-mapping">
            <a className={styles.card}>
              <h2>User Journey Mapping</h2>
            </a>
          </Link>

          <Link href="/personas">
            <a className={styles.card}>
              <h2>Personas</h2>
            </a>
          </Link>

          <Link href="/job-mapping">
            <a className={styles.card}>
              <h2>Job Mapping</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/sophiahooton"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed and developed by Sophia Portas
        </a>
      </footer>
    </div>
  );
};

export default Home;
